before_script:
  - node -v
  - npm -v


stages:
- test

test:node10:
  stage: test
  image: node:10-alpine
  script:
    - npm install
    - npm run build
    - npm run coverage


test:node8:
  stage: test
  image: node:8-alpine
  script:
    - npm install
    - npm run build
